/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChoicePanel: typeof import('./src/module/components/ChoicePanel.vue')['default']
    Message: typeof import('./src/module/components/Message.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
  }
}
